[package]
name = "flash-mint-provider-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.flash-mint-provider]
path = ".."

[dependencies.dharitri-wasm]
version = "0.6.3"

[dependencies.dharitri-wasm-debug]
version = "0.6.3"
